const CHARACTERS = {
  DUKE: 'duke',
  ASSASSIN: 'assassin',
  CAPTAIN: 'captain',
  AMBASSADOR: 'ambassador',
  COUNTESS: 'countess',
  INQUISITOR: 'inquisitor',
};

const PHASES = {
  WAITING_ACTION: 'WAITING_ACTION',
  WAITING_REACTIONS: 'WAITING_REACTIONS',
  WAITING_BLOCK_CHALLENGE: 'WAITING_BLOCK_CHALLENGE',
  RESOLVING: 'RESOLVING',
  LOSE_INFLUENCE: 'LOSE_INFLUENCE',
  EXCHANGE_CARDS: 'EXCHANGE_CARDS',
  INVESTIGATE: 'INVESTIGATE',
  GAME_OVER: 'GAME_OVER',
};

const ACTIONS = {
  INCOME: 'income',
  FOREIGN_AID: 'foreign_aid',
  COUP: 'coup',
  TAX: 'tax',
  ASSASSINATE: 'assassinate',
  EXTORT: 'extort',
  EXCHANGE: 'exchange',
  INVESTIGATE: 'investigate',
};

// quais personagens podem bloquear qual ação
const BLOCKERS = {
  [ACTIONS.FOREIGN_AID]: [CHARACTERS.DUKE],
  [ACTIONS.ASSASSINATE]: [CHARACTERS.COUNTESS],
  [ACTIONS.EXTORT]: [CHARACTERS.AMBASSADOR, CHARACTERS.INQUISITOR, CHARACTERS.CAPTAIN],
};

// qual ação pertence a qual personagem
const ACTION_CHARACTER = {
  [ACTIONS.TAX]: CHARACTERS.DUKE,
  [ACTIONS.ASSASSINATE]: CHARACTERS.ASSASSIN,
  [ACTIONS.EXTORT]: CHARACTERS.CAPTAIN,
  [ACTIONS.EXCHANGE]: [CHARACTERS.AMBASSADOR, CHARACTERS.INQUISITOR],
  [ACTIONS.INVESTIGATE]: CHARACTERS.INQUISITOR,
};

module.exports = { CHARACTERS, PHASES, ACTIONS, BLOCKERS, ACTION_CHARACTER };
